### PR TITLE
Adding a simple test suite, only a single basic test for now 

### PR DESCRIPTION
**Pull request by slavabez**
For the #2 issue. 

Added a config for testing the server with Jest. Uses the ts-jest package for doing testing without having to transpile to JS first. Uses supertest for testing Express.

Note! To make it easier to test I separated the app to it's own App.ts file. The index.ts file simply imports the App and starts it.

Only a simple test for now, makes sure the / directory returns an HTML file with a status 200.

### CODE REVIEW

**Comment by FlopiVG** [comment]
Wow really nice.

@slavabez can you change the name of index.test.ts to App.test.ts to keep file names to be tested?

**Comment by slavabez** [comment]
Done! Not much is tested yet, but this should be a good start.

**Comment by FlopiVG** [comment]
Srry I mean App.test.ts becouse you are importing App.ts

**Comment by FlopiVG** [comment]
Nice, thank you

**Comment by slavabez** [comment]
My bad :smile:

**Pull request merged**
